/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangTheUnveiledExperienceRouteImport } from './routes/$lang/the-unveiled-experience'
import { Route as LangSpanishConversationRouteImport } from './routes/$lang/spanish-conversation'
import { Route as LangMembershipsRouteImport } from './routes/$lang/memberships'
import { Route as LangFounderRouteImport } from './routes/$lang/founder'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangCommunityRouteImport } from './routes/$lang/community'
import { Route as LangBusinessBuildingBlocksRouteImport } from './routes/$lang/business-building-blocks'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as Lang10xProductiveRouteImport } from './routes/$lang/10x-productive'
import { Route as LangEventsIndexRouteImport } from './routes/$lang/events/index'
import { Route as LangBlogIndexRouteImport } from './routes/$lang/blog/index'
import { Route as LangEventsSlugRouteImport } from './routes/$lang/events/$slug'
import { Route as LangBlogSlugRouteImport } from './routes/$lang/blog/$slug'

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangTheUnveiledExperienceRoute =
  LangTheUnveiledExperienceRouteImport.update({
    id: '/the-unveiled-experience',
    path: '/the-unveiled-experience',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangSpanishConversationRoute = LangSpanishConversationRouteImport.update({
  id: '/spanish-conversation',
  path: '/spanish-conversation',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangMembershipsRoute = LangMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangFounderRoute = LangFounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCommunityRoute = LangCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBusinessBuildingBlocksRoute =
  LangBusinessBuildingBlocksRouteImport.update({
    id: '/business-building-blocks',
    path: '/business-building-blocks',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRouteRoute,
} as any)
const Lang10xProductiveRoute = Lang10xProductiveRouteImport.update({
  id: '/10x-productive',
  path: '/10x-productive',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangEventsIndexRoute = LangEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBlogIndexRoute = LangBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangEventsSlugRoute = LangEventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBlogSlugRoute = LangBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/10x-productive': typeof Lang10xProductiveRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/business-building-blocks': typeof LangBusinessBuildingBlocksRoute
  '/$lang/community': typeof LangCommunityRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/founder': typeof LangFounderRoute
  '/$lang/memberships': typeof LangMembershipsRoute
  '/$lang/spanish-conversation': typeof LangSpanishConversationRoute
  '/$lang/the-unveiled-experience': typeof LangTheUnveiledExperienceRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/events/$slug': typeof LangEventsSlugRoute
  '/$lang/blog/': typeof LangBlogIndexRoute
  '/$lang/events/': typeof LangEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/10x-productive': typeof Lang10xProductiveRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/business-building-blocks': typeof LangBusinessBuildingBlocksRoute
  '/$lang/community': typeof LangCommunityRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/founder': typeof LangFounderRoute
  '/$lang/memberships': typeof LangMembershipsRoute
  '/$lang/spanish-conversation': typeof LangSpanishConversationRoute
  '/$lang/the-unveiled-experience': typeof LangTheUnveiledExperienceRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/events/$slug': typeof LangEventsSlugRoute
  '/$lang/blog': typeof LangBlogIndexRoute
  '/$lang/events': typeof LangEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/10x-productive': typeof Lang10xProductiveRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/business-building-blocks': typeof LangBusinessBuildingBlocksRoute
  '/$lang/community': typeof LangCommunityRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/founder': typeof LangFounderRoute
  '/$lang/memberships': typeof LangMembershipsRoute
  '/$lang/spanish-conversation': typeof LangSpanishConversationRoute
  '/$lang/the-unveiled-experience': typeof LangTheUnveiledExperienceRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/events/$slug': typeof LangEventsSlugRoute
  '/$lang/blog/': typeof LangBlogIndexRoute
  '/$lang/events/': typeof LangEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/10x-productive'
    | '/$lang/about'
    | '/$lang/business-building-blocks'
    | '/$lang/community'
    | '/$lang/contact'
    | '/$lang/founder'
    | '/$lang/memberships'
    | '/$lang/spanish-conversation'
    | '/$lang/the-unveiled-experience'
    | '/$lang/'
    | '/$lang/blog/$slug'
    | '/$lang/events/$slug'
    | '/$lang/blog/'
    | '/$lang/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/10x-productive'
    | '/$lang/about'
    | '/$lang/business-building-blocks'
    | '/$lang/community'
    | '/$lang/contact'
    | '/$lang/founder'
    | '/$lang/memberships'
    | '/$lang/spanish-conversation'
    | '/$lang/the-unveiled-experience'
    | '/$lang'
    | '/$lang/blog/$slug'
    | '/$lang/events/$slug'
    | '/$lang/blog'
    | '/$lang/events'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/10x-productive'
    | '/$lang/about'
    | '/$lang/business-building-blocks'
    | '/$lang/community'
    | '/$lang/contact'
    | '/$lang/founder'
    | '/$lang/memberships'
    | '/$lang/spanish-conversation'
    | '/$lang/the-unveiled-experience'
    | '/$lang/'
    | '/$lang/blog/$slug'
    | '/$lang/events/$slug'
    | '/$lang/blog/'
    | '/$lang/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/the-unveiled-experience': {
      id: '/$lang/the-unveiled-experience'
      path: '/the-unveiled-experience'
      fullPath: '/$lang/the-unveiled-experience'
      preLoaderRoute: typeof LangTheUnveiledExperienceRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/spanish-conversation': {
      id: '/$lang/spanish-conversation'
      path: '/spanish-conversation'
      fullPath: '/$lang/spanish-conversation'
      preLoaderRoute: typeof LangSpanishConversationRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/memberships': {
      id: '/$lang/memberships'
      path: '/memberships'
      fullPath: '/$lang/memberships'
      preLoaderRoute: typeof LangMembershipsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/founder': {
      id: '/$lang/founder'
      path: '/founder'
      fullPath: '/$lang/founder'
      preLoaderRoute: typeof LangFounderRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/community': {
      id: '/$lang/community'
      path: '/community'
      fullPath: '/$lang/community'
      preLoaderRoute: typeof LangCommunityRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/business-building-blocks': {
      id: '/$lang/business-building-blocks'
      path: '/business-building-blocks'
      fullPath: '/$lang/business-building-blocks'
      preLoaderRoute: typeof LangBusinessBuildingBlocksRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/10x-productive': {
      id: '/$lang/10x-productive'
      path: '/10x-productive'
      fullPath: '/$lang/10x-productive'
      preLoaderRoute: typeof Lang10xProductiveRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/events/': {
      id: '/$lang/events/'
      path: '/events'
      fullPath: '/$lang/events/'
      preLoaderRoute: typeof LangEventsIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/blog/': {
      id: '/$lang/blog/'
      path: '/blog'
      fullPath: '/$lang/blog/'
      preLoaderRoute: typeof LangBlogIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/events/$slug': {
      id: '/$lang/events/$slug'
      path: '/events/$slug'
      fullPath: '/$lang/events/$slug'
      preLoaderRoute: typeof LangEventsSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/blog/$slug': {
      id: '/$lang/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$lang/blog/$slug'
      preLoaderRoute: typeof LangBlogSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  Lang10xProductiveRoute: typeof Lang10xProductiveRoute
  LangAboutRoute: typeof LangAboutRoute
  LangBusinessBuildingBlocksRoute: typeof LangBusinessBuildingBlocksRoute
  LangCommunityRoute: typeof LangCommunityRoute
  LangContactRoute: typeof LangContactRoute
  LangFounderRoute: typeof LangFounderRoute
  LangMembershipsRoute: typeof LangMembershipsRoute
  LangSpanishConversationRoute: typeof LangSpanishConversationRoute
  LangTheUnveiledExperienceRoute: typeof LangTheUnveiledExperienceRoute
  LangIndexRoute: typeof LangIndexRoute
  LangBlogSlugRoute: typeof LangBlogSlugRoute
  LangEventsSlugRoute: typeof LangEventsSlugRoute
  LangBlogIndexRoute: typeof LangBlogIndexRoute
  LangEventsIndexRoute: typeof LangEventsIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  Lang10xProductiveRoute: Lang10xProductiveRoute,
  LangAboutRoute: LangAboutRoute,
  LangBusinessBuildingBlocksRoute: LangBusinessBuildingBlocksRoute,
  LangCommunityRoute: LangCommunityRoute,
  LangContactRoute: LangContactRoute,
  LangFounderRoute: LangFounderRoute,
  LangMembershipsRoute: LangMembershipsRoute,
  LangSpanishConversationRoute: LangSpanishConversationRoute,
  LangTheUnveiledExperienceRoute: LangTheUnveiledExperienceRoute,
  LangIndexRoute: LangIndexRoute,
  LangBlogSlugRoute: LangBlogSlugRoute,
  LangEventsSlugRoute: LangEventsSlugRoute,
  LangBlogIndexRoute: LangBlogIndexRoute,
  LangEventsIndexRoute: LangEventsIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
