/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangMembershipsRouteImport } from './routes/$lang/memberships'
import { Route as LangFounderRouteImport } from './routes/$lang/founder'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangCommunityRouteImport } from './routes/$lang/community'
import { Route as LangBusinessBuildingBlocksRouteImport } from './routes/$lang/business-building-blocks'
import { Route as LangAboutRouteImport } from './routes/$lang/about'

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangMembershipsRoute = LangMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangFounderRoute = LangFounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCommunityRoute = LangCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBusinessBuildingBlocksRoute =
  LangBusinessBuildingBlocksRouteImport.update({
    id: '/business-building-blocks',
    path: '/business-building-blocks',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/business-building-blocks': typeof LangBusinessBuildingBlocksRoute
  '/$lang/community': typeof LangCommunityRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/founder': typeof LangFounderRoute
  '/$lang/memberships': typeof LangMembershipsRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/business-building-blocks': typeof LangBusinessBuildingBlocksRoute
  '/$lang/community': typeof LangCommunityRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/founder': typeof LangFounderRoute
  '/$lang/memberships': typeof LangMembershipsRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/business-building-blocks': typeof LangBusinessBuildingBlocksRoute
  '/$lang/community': typeof LangCommunityRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/founder': typeof LangFounderRoute
  '/$lang/memberships': typeof LangMembershipsRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/business-building-blocks'
    | '/$lang/community'
    | '/$lang/contact'
    | '/$lang/founder'
    | '/$lang/memberships'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang/business-building-blocks'
    | '/$lang/community'
    | '/$lang/contact'
    | '/$lang/founder'
    | '/$lang/memberships'
    | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/business-building-blocks'
    | '/$lang/community'
    | '/$lang/contact'
    | '/$lang/founder'
    | '/$lang/memberships'
    | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/memberships': {
      id: '/$lang/memberships'
      path: '/memberships'
      fullPath: '/$lang/memberships'
      preLoaderRoute: typeof LangMembershipsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/founder': {
      id: '/$lang/founder'
      path: '/founder'
      fullPath: '/$lang/founder'
      preLoaderRoute: typeof LangFounderRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/community': {
      id: '/$lang/community'
      path: '/community'
      fullPath: '/$lang/community'
      preLoaderRoute: typeof LangCommunityRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/business-building-blocks': {
      id: '/$lang/business-building-blocks'
      path: '/business-building-blocks'
      fullPath: '/$lang/business-building-blocks'
      preLoaderRoute: typeof LangBusinessBuildingBlocksRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangBusinessBuildingBlocksRoute: typeof LangBusinessBuildingBlocksRoute
  LangCommunityRoute: typeof LangCommunityRoute
  LangContactRoute: typeof LangContactRoute
  LangFounderRoute: typeof LangFounderRoute
  LangMembershipsRoute: typeof LangMembershipsRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangBusinessBuildingBlocksRoute: LangBusinessBuildingBlocksRoute,
  LangCommunityRoute: LangCommunityRoute,
  LangContactRoute: LangContactRoute,
  LangFounderRoute: LangFounderRoute,
  LangMembershipsRoute: LangMembershipsRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
