/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CeskyRouteImport } from './routes/cesky'
import { Route as BusinessBuildingBlocksRouteImport } from './routes/business-building-blocks'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'

const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CeskyRoute = CeskyRouteImport.update({
  id: '/cesky',
  path: '/cesky',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessBuildingBlocksRoute = BusinessBuildingBlocksRouteImport.update({
  id: '/business-building-blocks',
  path: '/business-building-blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRoute
  '/about': typeof AboutRoute
  '/business-building-blocks': typeof BusinessBuildingBlocksRoute
  '/cesky': typeof CeskyRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/memberships': typeof MembershipsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRoute
  '/about': typeof AboutRoute
  '/business-building-blocks': typeof BusinessBuildingBlocksRoute
  '/cesky': typeof CeskyRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/memberships': typeof MembershipsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRoute
  '/about': typeof AboutRoute
  '/business-building-blocks': typeof BusinessBuildingBlocksRoute
  '/cesky': typeof CeskyRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/founder': typeof FounderRoute
  '/memberships': typeof MembershipsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/about'
    | '/business-building-blocks'
    | '/cesky'
    | '/community'
    | '/contact'
    | '/founder'
    | '/memberships'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/about'
    | '/business-building-blocks'
    | '/cesky'
    | '/community'
    | '/contact'
    | '/founder'
    | '/memberships'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/about'
    | '/business-building-blocks'
    | '/cesky'
    | '/community'
    | '/contact'
    | '/founder'
    | '/memberships'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRoute
  AboutRoute: typeof AboutRoute
  BusinessBuildingBlocksRoute: typeof BusinessBuildingBlocksRoute
  CeskyRoute: typeof CeskyRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  FounderRoute: typeof FounderRoute
  MembershipsRoute: typeof MembershipsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cesky': {
      id: '/cesky'
      path: '/cesky'
      fullPath: '/cesky'
      preLoaderRoute: typeof CeskyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-building-blocks': {
      id: '/business-building-blocks'
      path: '/business-building-blocks'
      fullPath: '/business-building-blocks'
      preLoaderRoute: typeof BusinessBuildingBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRoute,
  AboutRoute: AboutRoute,
  BusinessBuildingBlocksRoute: BusinessBuildingBlocksRoute,
  CeskyRoute: CeskyRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  FounderRoute: FounderRoute,
  MembershipsRoute: MembershipsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
